name: Visitor Badge
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
  issues:
    types: [opened]
  delete:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Get visitor count
        id: visitor-count
        run: echo "::set-output name=count::$(curl -s https://api.countapi.xyz/hit/themrinmoy.readme.views | jq -r .value)"
      
      - name: Create visitor badge
        id: visitor-badge
        run: echo "count: $(curl -s https://api.countapi.xyz/hit/themrinmoy.readme.views/$(date +%s) | jq -r .value)" > badge.json

      - name: Upload badge
        uses: actions/upload-artifact@v2
        with:
          name: visitor-badge
          path: badge.json

      - name: Update README.md
        run: |
          count=$(jq -r .count badge.json)
          echo "Total Visitors: ${count}" > visitors.txt
          if grep -q "<!-- visitor-badge -->" README.md; then
            sed -i "/<!-- visitor-badge -->/c\![Visitor Count](https://visitor-badge.laobi.icu/badge?page_id=themrinmoy.themrinmoy&count=${count}) <!-- visitor-badge -->" README.md
          else
            echo "![Visitor Count](https://visitor-badge.laobi.icu/badge?page_id=themrinmoy.themrinmoy&count=${count}) <!-- visitor-badge -->" >> README.md
